version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: try-mysql:latest  # Provide the correct image reference here
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: badyal2003
    

  item_creation_microservice:
    image: try-item_creation_microservice:latest  # Provide the correct image reference here
    deploy:
      replicas: 3
    depends_on:
      - rabbitmq

  order_processing_microservice:
    image: try-order_processing_microservice:latest  # Provide the correct image reference here
    deploy:
      replicas: 3
    depends_on:
      - rabbitmq

  inventory_manager_microservice:
    image: try-inventory_manager_microservice:latest  # Provide the correct image reference here
    deploy:
      replicas: 3
    depends_on:
      - rabbitmq

  producer:
    image: try-producer:latest  # Provide the correct image reference here
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  healthcheck_microservice:
    image: try-healthcheck_microservice:latest  # Provide the correct image reference here
